# Generated by Django 5.2.13 on 2026-04-09 06:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='название')),
                ('event_date', models.DateField(verbose_name='дата')),
                ('event_type', models.CharField(choices=[('regular', 'Обычный'), ('tournament', 'Турнир')], default='regular', max_length=20)),
                ('price_per_game', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена за игру (₽), только для обычного')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'вечер',
                'verbose_name_plural': 'вечера',
                'ordering': ['-event_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GameTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название стола')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'стол',
                'verbose_name_plural': 'столы',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('default_price_per_game', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена за игру по умолчанию (₽)')),
            ],
            options={
                'verbose_name': 'глобальные настройки',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='имя')),
                ('nickname', models.CharField(db_index=True, max_length=120, verbose_name='никнейм')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='телефон')),
                ('social_url', models.URLField(blank=True, verbose_name='соцсеть')),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'игроки',
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='отображаемое имя')),
                ('login_code', models.CharField(blank=True, max_length=32, verbose_name='код входа')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('entity', models.CharField(blank=True, max_length=80)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('evening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='mafia.evening')),
            ],
            options={
                'ordering': ['game_number'],
                'unique_together': {('evening', 'game_number')},
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('prep', 'Подготовка'), ('voting', 'Голосование'), ('revoting', 'Переголосование'), ('lift_pending', 'Поднятие'), ('shooting', 'Стрельба'), ('testament', 'Завещание'), ('post_edit', 'Редактирование после игры')], default='prep', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('first_blood_done', models.BooleanField(default=False)),
                ('post_edit_unlocked', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=40)),
                ('judge_signature_note', models.CharField(blank=True, max_length=200)),
                ('protests', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('payment_counted', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mafia.game')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='mafia.gametable')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_sessions', to='mafia.player')),
            ],
            options={
                'ordering': ['game_id', 'table_id'],
                'unique_together': {('game', 'table')},
            },
        ),
        migrations.CreateModel(
            name='TestamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.JSONField(default=list)),
                ('completed', models.BooleanField(default=False)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testament', to='mafia.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='GameSessionPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('fouls', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('extra_points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('role', models.CharField(blank=True, choices=[('', '—'), ('peaceful', 'Мирный'), ('mafia', 'Мафия'), ('don', 'Дон'), ('sheriff', 'Шериф')], default='', max_length=20)),
                ('eliminated', models.BooleanField(default=False)),
                ('excluded_by_fouls', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='mafia.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia.player')),
            ],
            options={
                'ordering': ['seat_number'],
                'unique_together': {('session', 'player'), ('session', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='EveningPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.PositiveSmallIntegerField(default=0)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('evening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evening_players', to='mafia.evening')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evening_links', to='mafia.player')),
            ],
            options={
                'verbose_name': 'игрок вечера',
                'verbose_name_plural': 'игроки вечера',
                'unique_together': {('evening', 'player')},
            },
        ),
        migrations.CreateModel(
            name='ShootingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('target_seat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_miss', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shooting_rounds', to='mafia.gamesession')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('session', 'index')},
            },
        ),
        migrations.CreateModel(
            name='VotingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('main', 'Основное'), ('revote', 'Переголосование')], default='main', max_length=10)),
                ('nominations', models.JSONField(default=list)),
                ('votes', models.JSONField(default=dict)),
                ('is_tie', models.BooleanField(default=False)),
                ('eliminated_seat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_rounds', to='mafia.gamesession')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('session', 'index')},
            },
        ),
    ]
